

public enum TokenTypes {
   KEYWORD, IDENTIFIER, FLOAT, INTEGER, ADDOP, MULOP,
   SUBOP, DIVOP, LEFT_CURLY, RIGHT_CURLY, LEFT_PARA, RIGHT_PARA, LEFT_SQUARE,
   RIGHT_SQUARE, STRING_CONSTANT, OTHERS, ERROR, SEMICOLON, COMMA, ASSIGNMENT,
   RELOP
};
