
public enum TokenTypes {

   KW_INT, KW_FLOAT, KW_VOID, KW_RETURN, KW_WHILE, KW_IF, KW_ELSE, IDENTIFIER, FLOAT, INTEGER, ADDOP, MULOP,
   SUBOP, DIVOP, LEFT_CURLY, RIGHT_CURLY, LEFT_PARA, RIGHT_PARA, LEFT_SQUARE,
   RIGHT_SQUARE, STRING_CONSTANT, OTHERS, ERROR, SEMICOLON, COMMA, ASSIGNMENT,
   RELOP
};
